### PR TITLE
Fix bad Windows free in `dimshuffle.c`

### LINKED ISSUE #707: New DimShuffle C-code fails on Windows
This was first seen in https://github.com/pymc-devs/pymc/pull/5279

The following tests are failing on my Windows machine:
* `test_elemwise.py::TestDimShuffle::test_infer_shape`
* `test_elemwise.py::TestDimShuffle::test_too_big_rank`
* `test_elemwise.py::TestDimShuffle::test_c_views`

The first two tests which precede #701 pass before the relevant commit: https://github.com/aesara-devs/aesara/commit/e593b0ac57a0d56d4f6ffdd08d52c3be78ebf961 and fail after.

For sanity check, all tests in ` test_elemwise.py::TestBroadcast` work fine in main.

# Traceback 

When running `test_elemwise.py::TestDimShuffle::test_c_views`:

```python
C:\Users\ricar\miniconda3\envs\aesara-dev-custom\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py" --target test_elemwise.py::TestDimShuffle.test_c_views
Launching pytest with arguments test_elemwise.py::TestDimShuffle::test_c_views in C:\Users\ricar\Documents\aesara\tests\tensor

============================= test session starts =============================
platform win32 -- Python 3.9.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- C:\Users\ricar\miniconda3\envs\aesara-dev-custom\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\ricar\Documents\aesara, configfile: setup.cfg
collecting ... collected 1 item

test_elemwise.py::TestDimShuffle::test_c_views Windows fatal exception: code 0xc0000374

Current thread 0x00002704 (most recent call first):
  File "C:\Users\ricar\Documents\aesara\aesara\link\c\basic.py", line 1747 in __call__
  File "C:\Users\ricar\Documents\aesara\tests\tensor\test_elemwise.py", line 135 in test_c_views
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\python.py", line 183 in pytest_pyfunc_call
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\python.py", line 1641 in runtest
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 162 in pytest_runtest_call
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 255 in <lambda>
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 311 in from_call
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 254 in call_runtest_hook
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 215 in call_and_report
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 126 in runtestprotocol
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\runner.py", line 109 in pytest_runtest_protocol
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\main.py", line 348 in pytest_runtestloop
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\main.py", line 323 in _main
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\main.py", line 269 in wrap_session
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\main.py", line 316 in pytest_cmdline_main
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_callers.py", line 39 in _multicall
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_manager.py", line 80 in _hookexec
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\pluggy\_hooks.py", line 265 in __call__
  File "C:\Users\ricar\miniconda3\envs\aesara-dev-custom\lib\site-packages\_pytest\config\__init__.py", line 162 in main
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.1\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py", line 43 in <module>

Process finished with exit code -1073740940 (0xC0000374)
```

## Versions and main components

* Aesara version: main
* Aesara config (`python -c "import aesara; print(aesara.config)"`)
* Python version: 3.9.9
* Operating system: Windows 10
* How did you install Aesara: used the following conda enviroment.yml:

```yml
name: aesara-dev-custom
channels:
- conda-forge
- defaults
dependencies:
 # base dependencies (see install guide for Windows)
- aesara=2.3.3
- pip
- python=3.9
# Extra stuff for dev, testing and docs build
- ipython
- pre-commit
- pytest
```

And then removed aesara with `conda remove --force aesara` to use the local branch

### PR DESCRIPTION
**Pull request by brandonwillard**
This PR closes #707.

It looks like the `PyDimMem_FREE` macro can have two different behaviors, and one of them doesn't match the explicit use of `malloc`.  The changes here make the allocation and deallocation approaches match.

### CODE REVIEW

File: aesara/tensor/c_code/dimshuffle.c [hunk 1]
```diff
@@ -37,11 +37,10 @@ int APPLY_SPECIFIC(cpu_dimshuffle)(PyArrayObject *input, PyArrayObject **res,
   npy_intp N_shuffle = PyArray_SIZE(params->shuffle);
   npy_intp N_augment = PyArray_SIZE(params->augment);
   npy_intp N = N_augment + N_shuffle;
-  npy_intp *_reshape_shape = (npy_intp *)malloc(N * sizeof(npy_intp));
+  npy_intp *_reshape_shape = PyDimMem_NEW(N);
 
   if (_reshape_shape == NULL) {
     PyErr_NoMemory();
-    free(_reshape_shape);
```
Comment (twiecki) [inline aesara/tensor/c_code/dimshuffle.c:44]: Don't we need to free it another way?

Comment (brandonwillard) [reply aesara/tensor/c_code/dimshuffle.c:44]: I don't believe it should've been there in the first place, since `_reshape_shape` is `NULL` anyway.

**Comment by twiecki** [comment]
Awesome, and can we cut a new aesara release with this?

**Comment by brandonwillard** [comment]
> Awesome, and can we cut a new aesara release with this?

Just did.
